import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillFacebook, AiFillGoogleCircle, AiFillTwitterCircle} from 'react-icons/ai';
import Image from "next/image";
import cZhongli from "../public/cZhongli.webp";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio | KYN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-600">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-serif">Developed by KYN</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
              className="cursor-pointer text-2xl"/></li>
              <li><a 
              className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 font-serif"
              href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10"> 
            <h2 className="text-5xl py-2 text-teal-500 font-medium md:text-6xl font-serif">Khian & Rossiel</h2>
            <h3 className="text-2xl py-2 md:text-3xl text-black-200 font-serif">Developer and Designer.</h3>
            <p className="text-md py-5 leading-8 text-black-200 md:text-xl max-w-xl mx-auto font-serif">Students of Liceo de Cagayan University.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-black-600">
          <AiFillFacebook />
          <AiFillGoogleCircle />
          <AiFillTwitterCircle />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={cZhongli} layout="fill" objectFit="cover"/>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 md:text-6xl pb-10 pt-20 font-serif font-bold">Services we offer</h3>
            <p className="text-md py-2 leading-8 text-black-200 md:text-xl max-w-xl mx-auto">Hello we are students from Liceo de Cagayan University and a freelancer. We are still a  
            <spand className="text-teal-500"> beginner</spand> in this field but we will do our best to improve and provide a <spand className="text-teal-500"> quality of services.</spand>
            </p>
            <p className="text-md py-2 leading-8 text-black-200 md:text-xl max-w-xl mx-auto">
              We offer from a wide range of services, including programming and teaching. 
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 font-serif">Beautiful designs</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core designs theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools we use</h4>
              <p className="text-black-200 py-1">Photoshop</p>
              <p className="text-black-200 py-1">Canva</p>
              <p className="text-black-200 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 font-serif">Readable Codes</h3>
              <p className="py-2">
                Coding is fun and interesting if it is readable and easy to understand for those who wants to learn.
              </p>
              <h4 className="py-4 text-teal-600">Programming languages we use</h4>
              <p className="text-black-200 py-1">Java</p>
              <p className="text-black-200 py-1">JS</p>
              <p className="text-black-200 py-1">C++</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} /> 
              <h3 className="text-lg font-medium pt-8 pb-2 font-serif">Consulting</h3>
              <p className="py-2">
                If you need some advices or need someone to teach you or assist you, you can contact us. 
              </p>
              <h4 className="py-4 text-teal-600">I love i.t</h4>
              <p className="text-black-200 py-1">Google Meet</p>
              <p className="text-black-200 py-1">Zoom</p>
              <p className="text-black-200 py-1">Skype</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 pb-8 font-serif font-bold">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-black-200 md:text-xl max-w-xl mx-auto pb-20">Hello we are students from Liceo de Cagayan University and a freelancer. We are still a  
            <spand className="text-teal-500"> beginner</spand> in this field but we will do our best to improve and provide a <spand className="text-teal-500"> quality of services.</spand>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
